name: Test and build

on: push

jobs:
  test:
    name: Maven tests
    runs-on: ubuntu-18.04
    env:
      JAVA_HOME: /usr/lib/jvm/zulu-12-azure-amd64
      GIT_REF: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v1
      - run: mvn --no-transfer-progress clean test
