name: Test and deploy

on:
  push:
    branches:
      - mvn-deploy
    tags:
      - v*

jobs:
  test:
    name: Maven tests
    runs-on: ubuntu-18.04
    env:
      JAVA_HOME: /usr/lib/jvm/zulu-12-azure-amd64
      GIT_TAG: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v1
      - run: cat $HOME/.m2/settings.xml
      - run: mvn --no-transfer-progress clean test
#      - run: mvn --no-transfer-progress deploy -Drevision=${GIT_TAG}
